### ISSUE TITLE
The 'dimensions.json' file seems to be missing in the path 'GenshinTCGBuilder/scanner/'.

### ISSUE THREAD

**Issue by nighood** [Tomorrowdawn/GenshinTCGBuilder#1]
I uncommented the code for `T.pre_scan()` in my program, but kept getting an error message saying that the `'generated.json'` file could not be found. Later, I discovered that the `'dimensions.json'` file seemed to be missing from the `GenshinTCGBuilder/scanner/` directory, which prevented the program from scanning and extracting images to generate the `'generated.json'` file.

**Comment by Tomorrowdawn** [comment]
Thanks! I ignore *.json in .gitignore to avoid uploading too large file and it ignores scanner's json file as well, unexpectedly. I will reorganize file structure and fix it soon.

**Comment by nighood** [comment]
Thank you very much! Looking forward to your updates!

**Comment by Tomorrowdawn** [comment]
commit 5c7425e solved this issue
